### ISSUE TITLE
Crashes server and client looking for missing Tinker's Construct stuff (I don't have Tinker's installed).

### ISSUE THREAD

**Issue by Twilight13** [portablejim/VeinMinerModIntegration#3]
I don't have Tinker's installed, but it seems to be crashing because it's looking for a Tinker's class.

Time: 7/27/15 9:35 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/modifier/ItemModifier
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:502)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
    at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/modifier/ItemModifier
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
    at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.modifier.ItemModifier
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.NullPointerException

**Comment by huntdogy** [comment]
well get tinkers installed since its a addon to tinkers

**Comment by SanityCh3ck** [comment]
It's supposed to work without TiCon though, to get the Enchantment requirement. I currently have the same issue, and would very much appreciate this getting fixed so I can use VeinMiner in my pack.
Please, @portablejim ?

**Comment by TomeWyrm** [comment]
Yep. Still an issue. I too would like to make VeinMine an enchantment without having to install and neuter Tinkers to do so.

**Comment by TheLoneWolfling** [comment]
...Still an issue.

I want the Veinminer enchantment, but I don't want TC.
